/**
 * Demo corpus — verbatim public text from the Electronic Code of Federal
 * Regulations (ecfr.gov), covering tax, accounting and investing. Public domain
 * U.S. government text, reproduced unedited and paginated for the demo viewer.
 *
 * Generated file. Do not hand-edit; the text must stay verbatim.
 */

export interface DemoDoc {
  id: string;
  name: string;
  citation: string;
  topic: 'Tax' | 'Accounting' | 'Investing';
  pages: string[];
}

export const DEMO_DOCS: DemoDoc[] = [
  {
    id: "tax-162-1",
    name: "Business Expense Deductions",
    citation: "26 CFR 1.162-1",
    topic: "Tax",
    pages: [
      "\u00a7 1.162-1 Business expenses. (a) In general. Business expenses deductible from gross income include the ordinary and necessary expenditures directly connected with or pertaining to the taxpayer's trade or business, except items which are used as the basis for a deduction or a credit under provisions of law other than section 162. The cost of goods purchased for resale, with proper adjustment for opening and closing inventories, is deducted from gross sales in computing gross income. See paragraph (a) of \u00a7 1.161-3. Among the items included in business expenses are management expenses, commissions (but see section 263 and the regulations thereunder), labor, supplies, incidental repairs, operating expenses of automobiles used in the trade or business, traveling expenses while away from home solely in the pursuit of a trade or business (see \u00a7 1.162-2), advertising and other selling expenses, together with insurance premiums against fire, storm, theft, accident, or other similar losses in the case of a business, and rental for the use of business property.",
      "No such item shall be included in business expenses, however, to the extent that it is used by the taxpayer in computing the cost of property included in its inventory or used in determining the gain or loss basis of its plant, equipment, or other property. See section 1054 and the regulations thereunder. A deduction for an expense paid or incurred after December 30, 1969, which would otherwise be allowable under section 162 shall not be denied on the grounds that allowance of such deduction would frustrate a sharply defined public policy. See section 162(c), (f), and (g) and the regulations thereunder. The full amount of the allowable deduction for ordinary and necessary expenses in carrying on a business is deductible, even though such expenses exceed the gross income derived during the taxable year from such business.",
      "In the case of any sports program to which section 114 (relating to sports programs conducted for the American National Red Cross) applies, expenses described in section 114(a)(2) shall be allowable as deductions under section 162(a) only to the extent that such expenses exceed the amount excluded from gross income under section 114(a). (b) Cross references. (1) For charitable contributions by individuals and corporations not deductible under section 162, see \u00a7 1.162-15. (2) For items not deductible, see sections 261-276, inclusive, and the regulations thereunder. (3) For research and experimental expenditures, see section 174 and regulations thereunder. (4) For soil and water conservation expenditures, see section 175 and regulations thereunder. (5) For expenditures attributable to grant or loan by United States for encouragement of exploration for, or development or mining of, critical and strategic minerals or metals, see section 621 and regulations thereunder.",
      "(6) For treatment of certain rental payments with respect to public utility property, see section 167(1) and \u00a7 1.167(1)-3. (7) For limitations on the deductibility of miscellaneous itemized deductions, see section 67 and \u00a7\u00a7 1.67-1T through 1.67-4T. (8) For the timing of deductions with respect to notional principal contracts. see \u00a7 1.446-3. [T.D. 6500, 25 FR 11402, Nov. 26, 1960, as amended by T.D. 6690, 28 FR 12253, Nov. 19, 1963; T.D. 6996, 34 FR 835, Jan. 18, 1969; T.D. 7315, 39 FR 20203, June 7, 1974; T.D. 7345, 40 FR 7437, Feb. 20, 1975; T.D. 8189, 53 FR 9881, Mar. 28, 1988; T.D. 8491, 58 FR 53128, Oct. 14, 1993]",
    ],
  },
  {
    id: "tax-274-12",
    name: "Meal & Beverage Deduction Limits",
    citation: "26 CFR 1.274-12",
    topic: "Tax",
    pages: [
      "\u00a7 1.274-12 Limitation on deductions for certain food or beverage expenses paid or incurred after December 31, 2017. (a) Food or beverage expenses \u2014(1) In general. Except as provided in this section, no deduction is allowed for the expense of any food or beverages provided by the taxpayer (or an employee of the taxpayer) unless\u2014 (i) The expense is not lavish or extravagant under the circumstances; (ii) The taxpayer, or an employee of the taxpayer, is present at the furnishing of such food or beverages; and (iii) The food or beverages are provided to the taxpayer or a business associate. (2) Only 50 percent of food or beverage expenses allowed as deduction. Except as provided in this section, the amount allowable as a deduction for any food or beverage expense described in paragraph (a)(1) of this section may not exceed 50 percent of the amount of the expense that otherwise would be allowable. (3) Examples. The following examples illustrate the application of paragraph (a)(1) and (2) of this section.",
      "In each example, assume that the food or beverage expenses are ordinary and necessary expenses under section 162(a) that are paid or incurred during the taxable year in carrying on a trade or business and are not lavish or extravagant under the circumstances. Also assume that none of the exceptions in paragraph (c) of this section apply. (i) Example 1. Taxpayer A takes client B out to lunch. Under section 274(k) and (n) and paragraph (a) of this section, A may deduct 50 percent of the food or beverage expenses. (ii) Example 2. Taxpayer C takes employee D out to lunch. Under section 274(k) and (n) and paragraph (a) of this section, C may deduct 50 percent of the food or beverage expenses. (iii) Example 3. Taxpayer E holds a business meeting at a hotel during which food and beverages are provided to attendees. Expenses for the business meeting, other than the cost of food and beverages, are not subject to the deduction limitations in section 274 and are deductible if they meet the requirements for deduction under section 162.",
      "Under section 274(k) and (n) and paragraph (a) of this section, E may deduct 50 percent of the food and beverage expenses. (iv) Example 4. The facts are the same as in paragraph (a)(3)(iii) of this section (Example 3), except that all the attendees of the meeting are employees of E. Expenses for the business meeting, other than the cost of food and beverages, are not subject to the deduction limitations in section 274 and are deductible if they meet the requirements for deduction under section 162. Under section 274(k) and (n) and paragraph (a) of this section, E may deduct 50 percent of the food and beverage expenses. The exception in section 274(e)(5) does not apply to food and beverage expenses under section 274(k) and (n). (4) Special rules for travel meals. (i) In general. Food or beverage expenses paid or incurred while traveling away from home in pursuit of a trade or business generally are subject to the deduction limitations in section 274(k) and (n) and paragraph (a)(1) and (2) of this section, as well as the substantiation requirements in section 274(d).",
      "In addition, travel expenses generally are subject to the limitations in section 274(m)(1), (2), and (3). (ii) Substantiation. Except as provided in this section, no deduction is allowed for the expense of any food or beverages paid or incurred while traveling away from home in pursuit of a trade or business unless the taxpayer meets the substantiation requirements in section 274(d). (iii) Travel meal expenses of spouse, dependent or others. No deduction is allowed under chapter 1 of the Internal Revenue Code (Code), except under section 217 for certain members of the Armed Forces of the United States, for the expense of any food or beverages paid or incurred with respect to a spouse, dependent, or other individual accompanying the taxpayer, or an officer or employee of the taxpayer, on business travel, unless\u2014 (A) The spouse, dependent, or other individual is an employee of the taxpayer; (B) The travel of the spouse, dependent, or other individual is for a bona fide business purpose of the taxpayer;",
      "and (C) The expenses would otherwise be deductible by the spouse, dependent or other individual. (D) Example. The following example illustrates the application of paragraph (a)(4)(iii) of this section: ( 1 ) Example. Taxpayer F, a sole proprietor, and Taxpayer F's spouse travel from New York to Boston to attend a series of business meetings related to F's trade or business. F's spouse is not an employee of F, does not travel to Boston for a bona fide business purpose of F, and the expenses would not otherwise be deductible. While in Boston, F and F's spouse go out to dinner. Under section 274(m)(3) and paragraph (a)(4)(iii) of this section, the expenses associated with the food and beverages consumed by F's spouse are not deductible. Therefore, the cost of F's spouse's dinner is not deductible. F may deduct 50 percent of the expense associated with the food and beverages F consumed while on business travel if F meets the requirements in sections 162 and 274, including section 274(k) and (d). ( 2 ) [Reserved] (b) Definitions.",
      "Except as otherwise provided in this section, the following definitions apply for purposes of section 274(k) and (n), \u00a7 1.274-11(b)(1)(ii) and (d), and this section: (1) Food or beverages. Food or beverages means all food and beverage items, regardless of whether characterized as meals, snacks, or other types of food and beverages, and regardless of whether the food and beverages are treated as de minimis fringes under section 132(e). (2) Food or beverage expenses. Food or beverage expenses mean the full cost of food or beverages, including any delivery fees, tips, and sales tax. In the case of employer-provided meals furnished at an eating facility on the employer's business premises, food or beverage expenses do not include expenses for the operation of the eating facility such as salaries of employees preparing and serving meals and other overhead costs. (3) Business associate.",
      "Business associate means a person with whom the taxpayer could reasonably expect to engage or deal in the active conduct of the taxpayer's trade or business such as the taxpayer's customer, client, supplier, employee, agent, partner, or professional adviser, whether established or prospective. (4) Independent contractor. For purposes of the reimbursement or other expense allowance arrangements described in paragraph (c)(2)(ii) of this section, independent contractor means a person who is not an employee of the payor. (5) Client or customer. For purposes of the reimbursement or other expense allowance arrangements described in paragraph (c)(2)(ii) of this section, client or customer of an independent contractor means a person who receives services from an independent contractor and enters into a reimbursement or other expense allowance arrangement with the independent contractor. (6) Payor.",
      "For purposes of the reimbursement or other expense allowance arrangements described in paragraph (c)(2)(ii) of this section, payor means a person that enters into a reimbursement or other expense allowance arrangement with an employee and may include an employer, its agent, or a third party. (7) Reimbursement or other expense allowance arrangement. For purposes of the reimbursement or other expense allowance arrangements described in paragraph (c)(2)(ii) of this section, reimbursement or other expense allowance arrangement means\u2014 (i) For purposes of paragraph (c)(2)(ii)(B) of this section, an arrangement under which an employee receives an advance, allowance, or reimbursement from a payor for expenses the employee pays or incurs;",
      "and (ii) For purposes of paragraph (c)(2)(ii)(C) of this section, an arrangement under which an independent contractor receives an advance, allowance, or reimbursement from a client or customer for expenses the independent contractor pays or incurs if either\u2014 (A) A written agreement between the parties expressly states that the client or customer will reimburse the independent contractor for expenses that are subject to the limitations on deductions described in paragraph (a) of this section; or (B) A written agreement between the parties expressly identifies the party subject to the limitations. (8) Primarily consumed. For purposes of paragraph (c)(2)(iv) of this section, primarily consumed means greater than 50 percent of actual or reasonably estimated consumption. (9) General public. For purposes of paragraph (c)(2)(iv) of this section, the general public includes, but is not limited to, customers, clients, and visitors.",
      "The general public does not include employees, partners, 2-percent shareholders of S corporations (as defined in section 1372(b)), or independent contractors of the taxpayer. Also, the guests on an exclusive list of guests are not the general public. (c) Exceptions \u2014(1) In general. The limitations on the deduction of food or beverage expenses in paragraph (a) of this section do not apply to any expense described in paragraph (c)(2) of this section. These expenses are deductible to the extent allowable under chapter 1 of the Code (chapter 1). (2) Exceptions \u2014(i) Expenses treated as compensation \u2014(A) Expenses includible in income of persons who are employees and are not specified individuals.",
      "In accordance with section 274(e)(2)(A), and except as provided in paragraph (c)(2)(i)(D) of this section, an expense paid or incurred by a taxpayer for food or beverages, if an employee who is not a specified individual is the recipient of the food or beverages, is not subject to the deduction limitations in paragraph (a) of this section to the extent that the taxpayer\u2014 ( 1 ) Properly treats the expense relating to the recipient of food or beverages as compensation to an employee under chapter 1 and as wages to the employee for purposes of chapter 24 of the Code (chapter 24).; and ( 2 ) Treats the proper amount as compensation to the employee under \u00a7 1.61-21. (B) Expenses includible in income of persons who are not employees and are not specified individuals.",
      "In accordance with section 274(e)(9), and except as provided in paragraph (c)(2)(i)(D) of this section, an expense paid or incurred by a taxpayer for food or beverages is not subject to the deduction limitations in paragraph (a) of this section to the extent that the expenses are properly included in income as compensation for services rendered by, or as a prize or award under section 74 to, a recipient of the expense who is not an employee of the taxpayer and is not a specified individual. The preceding sentence does not apply to any amount paid or incurred by the taxpayer if the amount is required to be included, or would be so required except that the amount is less than $600, in any information return filed by such taxpayer under part III of subchapter A of chapter 61 of the Code and is not so included. (C) Specified Individuals.",
      "In accordance with section 274(e)(2)(B), in the case of a specified individual (as defined in section 274(e)(2)(B)(ii)), the deduction limitations in paragraph (a) of this section do not apply to an expense for food or beverages of the specified individual to the extent that the amount of the expense does not exceed the sum of\u2014 ( 1 ) The amount treated as compensation to the specified individual under chapter 1 and as wages to the specified individual for purposes of chapter 24 (if the specified individual is an employee) or as compensation for services rendered by, or as a prize or award under section 74 to, a recipient of the expense (if the specified individual is not an employee); and ( 2 ) Any amount the specified individual reimburses the taxpayer. (D) Expenses for which an amount is excluded from income or is less than the proper amount.",
      "Notwithstanding paragraphs (c)(2)(i)(A) and (B) of this section, in the case of an expense paid or incurred by a taxpayer for food or beverages for which an amount is wholly or partially excluded from a recipients' income under any section of subtitle A of the Code (other than because the amount is reimbursed by the recipient), or for which an amount included in compensation and wages to an employee (or as income to a nonemployee) is less than the amount required to be included under \u00a7 1.61-21, the deduction limitations in paragraph (a) of this section do not apply to the extent that the amount of the expense does not exceed the sum of\u2014 ( 1 ) The amount treated as compensation to the employee under chapter 1 (or as income to a nonemployee) and as wages to the employee for purposes of chapter 24; and ( 2 ) Any amount the recipient reimburses the taxpayer. (E) Examples. The following examples illustrate the application of paragraph (c)(2)(i) of this section.",
      "In each example, assume that the food or beverage expenses are ordinary and necessary expenses under section 162(a) that are paid or incurred during the taxable year in carrying on a trade or business. ( 1 ) Example 1. Employer G provides food and beverages to its non-specified individual employees without charge at a company cafeteria on its premises. The food and beverages do not meet the definition of a de minimis fringe under section 132(e). Thus, G treats the full fair market value of the food and beverage expenses as compensation and wages, and properly determines this amount under \u00a7 1.61-21. Under section 274(e)(2) and paragraph (c)(2)(i)(A) of this section, the expenses associated with the food and beverages provided to the employees are not subject to the 50 percent deduction limitation in paragraph (a) of this section. Thus, G may deduct 100 percent of the food and beverage expenses. ( 2 ) Example 2. The facts are the same as in paragraph (c)(2)(i)(E)( 1 ) of this section ( Example 1), except that each employee pays $8 per day for the food and beverages.",
      "The fair market value of the food and beverages is $10 per day, per employee. G incurs $9 per day, per employee for the food and beverages. G treats the food and beverage expenses as compensation and wages, and properly determines the amount of the inclusion under \u00a7 1.61-21 to be $2 per day, per employee ($10 fair market value\u2212$8 reimbursed by the employee = $2). Therefore, under paragraph (c)(2)(i)(A) of this section, G may deduct 100 percent of the food and beverage expenses, or $9 per day, per employee. ( 3 ) Example 3. Employer H provides meals to its employees without charge. The meals are properly excluded from the employees' income under section 119 as meals provided for the convenience of the employer. Under \u00a7 1.61-21(b)(1), an employee must include in gross income the amount by which the fair market value of a fringe benefit exceeds the sum of the amount, if any, paid for the benefit by or on behalf of the recipient, and the amount, if any, specifically excluded from gross income by some other section of subtitle A of the Code.",
      "Because the entire value of the employees' meals is excluded from the employees' income under section 119, the fair market value of the fringe benefit does not exceed the amount excluded from gross income under subtitle A of the Code, so there is nothing to be included in the employees' income under \u00a7 1.61-21. Thus, the exception in section 274(e)(2) and paragraph (c)(2)(i) of this section does not apply and, assuming no other exceptions provided under section 274(n)(2) and paragraph (c)(2) of this section apply, H may deduct only 50 percent of the expenses for the food and beverages provided to employees. In addition, the limitations in section 274(k)(1) and paragraph (a)(1) of this section apply because none of the exceptions in section 274(k)(2) and paragraph (c)(2) of this section apply. (ii) Reimbursed food or beverage expenses \u2014(A) In general.",
      "In accordance with section 274(e)(3), in the case of expenses for food or beverages paid or incurred by one person in connection with the performance of services for another person, whether or not the other person is an employer, under a reimbursement or other expense allowance arrangement, the deduction limitations in paragraph (a) of this section apply either to the person who makes the expenditure or to the person who actually bears the expense, but not to both. If an expense of a type described in paragraph (c)(2)(ii) of this section properly constitutes a dividend paid to a shareholder, unreasonable compensation paid to an employee, a personal expense, or other nondeductible expense, nothing in this exception prevents disallowance of the deduction to the taxpayer under other provisions of the Code. (B) Reimbursement arrangements involving employees.",
      "In the case of expenses paid or incurred by an employee for food or beverages in performing services as an employee under a reimbursement or other expense allowance arrangement with a payor, the limitations on deductions in paragraph (a) of this section apply\u2014 ( 1 ) To the employee to the extent the employer treats the reimbursement or other payment of the expense on the employer's income tax return as originally filed as compensation paid to the employee and as wages to the employee for purposes of withholding under chapter 24 relating to collection of income tax at source on wages; or ( 2 ) To the payor to the extent the reimbursement or other payment of the expense is not treated as compensation and wages paid to the employee in the manner provided in paragraph (c)(2)(ii)(B)( 1 ) of this section. However, see paragraph (c)(2)(ii)(C) of this section if the payor receives a payment from a third party that may be treated as a reimbursement arrangement under that paragraph. (C) Reimbursement arrangements involving persons that are not employees.",
      "In the case of expenses for food or beverages paid or incurred by an independent contractor in connection with the performance of services for a client or customer under a reimbursement or other expense allowance arrangement with the independent contractor, the limitations on deductions in paragraph (a) of this section apply to the party expressly identified in an agreement between the parties as subject to the limitations. If an agreement between the parties does not expressly identify the party subject to the limitations, then the deduction limitations in paragraph (a) of this section apply\u2014 ( 1 ) To the independent contractor (which may be a payor) to the extent the independent contractor does not account to the client or customer within the meaning of section 274(d); or ( 2 ) To the client or customer if the independent contractor accounts to the client or customer within the meaning of section 274(d). (D) Section 274(d) substantiation.",
      "If the reimbursement or other expense allowance arrangement involves persons who are not employees and the agreement between the parties does not expressly identify the party subject to the limitations on deductions in paragraph (a) of this section, the limitations on deductions in paragraph (a) of this section apply to the independent contractor unless the independent contractor accounts to the client or customer with substantiation that satisfies the requirements of section 274(d). (E) Examples. The following examples illustrate the application of paragraph (c)(2)(ii) of this section. ( 1 ) Example 1. ( i ) Employee I performs services under an arrangement in which J, an employee leasing company, pays I a per diem allowance of $10x for each day that I performs services for J's client, K, while traveling away from home. The per diem allowance is a reimbursement of travel expenses for food or beverages that I pays in performing services as an employee.",
      "J enters into a written agreement with K under which K agrees to reimburse J for any substantiated reimbursements for travel expenses, including meal expenses, that J pays to I. The agreement does not expressly identify the party that is subject to the limitations on deductions in paragraph (a) of this section. I performs services for K while traveling away from home for 10 days and provides J with substantiation that satisfies the requirements of section 274(d) of $100x of meal expenses incurred by I while traveling away from home. J pays I $100x to reimburse those expenses pursuant to their arrangement. J delivers a copy of I's substantiation to K. K pays J $300x, which includes $200x compensation for services and $100x as reimbursement of J's payment of I's travel expenses for meals. Neither J nor K treats the $100x paid to I as compensation or wages. ( ii ) Under paragraph (b)(7)(i) of this section, I and J have established a reimbursement or other expense allowance arrangement for purposes of paragraph (c)(2)(ii)(B) of this section.",
      "Because the reimbursement payment is not treated as compensation and wages paid to I, under section 274(e)(3)(A) and paragraph (c)(2)(ii)(B)( 1 ) of this section, I is not subject to the limitations on deductions in paragraph (a) of this section. Instead, under paragraph (c)(2)(ii)(B)( 2 ) of this section, J, the payor, is subject to limitations on deductions in paragraph (a) of this section unless J can meet the requirements of section 274(e)(3)(B) and paragraph (c)(2)(ii)(C) of this section. ( iii ) Because the agreement between J and K expressly states that K will reimburse J for substantiated reimbursements for travel expenses that J pays to I, under paragraph (b)(7)(ii)(A) of this section, J and K have established a reimbursement or other expense allowance arrangement for purposes of paragraph (c)(2)(ii)(C) of this section. J accounts to K for K's reimbursement in the manner required by section 274(d) by delivering to K a copy of the substantiation J received from I.",
      "Therefore, under section 274(e)(3)(B) and paragraph (c)(2)(ii)(C)( 2 ) of this section, K and not J is subject to the deduction limitations in paragraph (a) of this section. ( 2 ) Example 2. ( i ) The facts are the same as in paragraph (c)(2)(ii)(E)( 1 ) of this section ( Example 1) except that, under the arrangements between I and J and between J and K, I provides the substantiation of the expenses directly to K, and K pays the per diem directly to I. ( ii ) Under paragraph (b)(7)(i) of this section, I and K have established a reimbursement or other expense allowance arrangement for purposes of paragraph (c)(2)(ii)(C) of this section. Because I substantiates directly to K and the reimbursement payment was not treated as compensation and wages paid to I, under section 274(e)(3)(A) and paragraph (c)(2)(ii)(C)( 1 ) of this section, I is not subject to the limitations on deductions in paragraph (a) of this section. Under paragraph (c)(2)(ii)(C)( 2 ) of this section, K, the payor, is subject to the limitations on deductions in paragraph (a) of this section. ( 3 ) Example 3.",
      "( i ) The facts are the same as in paragraph (c)(2)(ii)(E)( 1 ) of this section ( Example 1), except that the written agreement between J and K expressly provides that the limitations of this section will apply to K. ( ii ) Under paragraph (b)(7)(ii)(B) of this section, J and K have established a reimbursement or other expense allowance arrangement for purposes of paragraph (c)(2)(ii)(C) of this section. Because the agreement provides that the 274 deduction limitations apply to K, under section 274(e)(3)(B) and paragraph (c)(2)(ii)(C) of this section, K and not J is subject to the limitations on deductions in paragraph (a) of this section. ( 4 ) Example 4. ( i ) The facts are the same as in (c)(2)(ii)(E)( 1 ) of this section ( Example 1), except that the agreement between J and K does not provide that K will reimburse J for travel expenses. ( ii ) The arrangement between J and K is not a reimbursement or other expense allowance arrangement within the meaning of section 274(e)(3)(B) and paragraph (b)(7)(ii) of this section.",
      "Therefore, even though J accounts to K for the expenses, J is subject to the limitations on deductions in paragraph (a) of this section. (iii) Recreational expenses for employees \u2014(A) In general. In accordance with section 274(e)(4), any food or beverage expense paid or incurred by a taxpayer for a recreational, social, or similar activity, primarily for the benefit of a taxpayer's employees (other than employees who are highly compensated employees (within the meaning of section 414(q))) is not subject to the deduction limitations in paragraph (a) of this section. For purposes of this paragraph (c)(2)(iii), an employee owning less than a 10-percent interest in the taxpayer's trade or business is not considered a shareholder or other owner, and for such purposes an employee is treated as owning any interest owned by a member of the employee's family (within the meaning of section 267(c)(4)).",
      "Any expense for food or beverages that is made under circumstances which discriminate in favor of highly compensated employees is not considered to be made primarily for the benefit of employees generally. An expense for food or beverages is not to be considered outside of the exception of this paragraph (c)(2)(iii) merely because, due to the large number of employees involved, the provision of food or beverages is intended to benefit only a limited number of employees at one time, provided the provision of food or beverages does not discriminate in favor of highly compensated employees. This exception applies to expenses paid or incurred for events such as holiday parties, annual picnics, or summer outings. This exception does not apply to expenses for meals the value of which is excluded from employees' income under section 119 because the meals are provided for the convenience of the employer and are therefore not primarily for the benefit of the taxpayer's employees. (B) Examples. The following examples illustrate the application of this paragraph (c)(2)(iii).",
      "In each example, assume that the food or beverage expenses are ordinary and necessary expenses under section 162(a) that are paid or incurred during the taxable year in carrying on a trade or business. ( 1 ) Example 1. Employer L invites all employees to a holiday party in a hotel ballroom that includes a buffet dinner and an open bar. Under section 274(e)(4), this paragraph (c)(2)(iii), and \u00a7 1.274-11(c), the cost of the party, including food and beverage expenses, is not subject to the deduction limitations in paragraph (a) of this section because the holiday party is a recreational, social, or similar activity primarily for the benefit of non-highly compensated employees. Thus, L may deduct 100 percent of the cost of the party. ( 2 ) Example 2. The facts are the same as in paragraph (c)(2)(iii)(B)( 1 ) of this section ( Example 1), except that Employer L invites only highly-compensated employees to the holiday party, and the invoice provided by the hotel lists the costs for food and beverages separately from the cost of the rental of the ballroom.",
      "The costs reflect the venue's usual selling price for food or beverages. The exception in this paragraph (c)(2)(iii) does not apply to the rental of the ballroom or the food and beverage expenses because L invited only highly-compensated employees to the holiday party. However, under \u00a7 1.274-11(b)(1)(ii), the food and beverage expenses are not treated as entertainment. Therefore, L is not subject to the full disallowance for its separately stated food and beverage expense under section 274(a)(1) and \u00a7 1.274-11(a). Unless another exception in section 274(n)(2) and paragraph (c)(2) of this section applies, L may deduct only 50 percent of the food and beverage costs under paragraph (a)(2) of this section. In addition, the limitations in section 274(k)(1) and paragraph (a)(1) of this section apply because none of the exceptions in section 274(k)(2) and paragraph (c)(2) of this section apply. ( 3 ) Example 3. Employer M provides free coffee, soda, bottled water, chips, donuts, and other snacks in a break room available to all employees.",
      "A break room is not a recreational, social, or similar activity primarily for the benefit of the employees, even if some socializing related to the food and beverages provided occurs. Thus, the exception in section 274(e)(4) and this paragraph (c)(2)(iii) does not apply and unless another exception in section 274(n)(2) and paragraph (c)(2) of this section applies, M may deduct only 50 percent of the expenses for food and beverages provided in the break room under paragraph (a)(2) of this section. In addition, the limitations in section 274(k)(1) and paragraph (a)(1) of this section apply because none of the exceptions in section 274(k)(2) and paragraph (c)(2) of this section apply. ( 4 ) Example 4. Employer N has a written policy that employees in a certain medical services-related position must be available for emergency calls due to the nature of the position that requires frequent emergency responses. Because these emergencies can and do occur during meal periods, N furnishes food and beverages to employees in this position without charge in a cafeteria on N's premises.",
      "N excludes food and beverage expenses from the employees' income as meals provided for the convenience of the employer excludable under section 119. Because these food and beverages are furnished for the employer's convenience, and therefore are not primarily for the benefit of the employees, the exception in section 274(e)(4) and this paragraph (c)(2)(iii) does not apply, even if some socializing related to the food and beverages provided occurs. Further, the exception in section 274(e)(2) and paragraph (c)(2)(i) of this section does not apply. Thus, unless another exception in section 274(n)(2) and paragraph (c)(2) of this section applies, N may deduct only 50 percent of the expenses for food and beverages provided to employees in the cafeteria under paragraph (a)(2) of this section. In addition, the limitations in section 274(k)(1) and paragraph (a)(1) of this section apply because none of the exceptions in section 274(k)(2) and paragraph (c)(2) of this section apply. ( 5 ) Example 5. Employer O invites an employee and a client to dinner at a restaurant.",
      "Because it is the birthday of the employee, O orders a special dessert in celebration. Because the meal is a business meal, and therefore not primarily for the benefit of the employee, the exception in section 274(e)(4) and this paragraph (c)(2)(iii) does not apply, even though an employee social activity in the form of a birthday celebration occurred during the meal. Thus, unless another exception in section 274(n)(2) and paragraph (c)(2) of this section applies, O may deduct only 50 percent of the meal expense. In addition, the limitations in section 274(k)(1) and paragraph (a)(1) of this section apply because none of the exceptions in section 274(k)(2) and paragraph (c)(2) of this section apply. (iv) Items available to the public \u2014(A) In general. In accordance with section 274(e)(7), any expense paid or incurred by a taxpayer for food or beverages to the extent the food or beverages are made available to the general public is not subject to the deduction limitations in paragraph (a) of this section.",
      "If a taxpayer provides food or beverages to employees, this exception applies to the entire amount of expenses for those food or beverages if the same type of food or beverages is provided to, and are primarily consumed by, the general public. (B) Examples. The following examples illustrate the application of this paragraph (c)(2)(iv). In each example, assume that the food and beverage expenses are ordinary and necessary expenses under section 162(a) that are paid or incurred during the taxable year in carrying on a trade or business. ( 1 ) Example 1. Employer P is a real estate agent and provides refreshments at an open house for a home available for sale to the public. The refreshments are consumed by P's employees, potential buyers of the property, and other real estate agents.",
      "Under section 274(e)(7) and this paragraph (c)(2)(iv), the expenses associated with the refreshments are not subject to the deduction limitations in paragraph (a) of this section if P determines that over 50 percent of the food and beverages are actually or reasonably estimated to be consumed by potential buyers and other real estate agents. If more than 50 percent of the food and beverages are not actually or reasonably estimated to be consumed by the general public, only the costs attributable to the food and beverages provided to the general public are excepted under section 274(e)(7) and this paragraph (c)(2)(iv). In addition, the limitations in section 274(k)(1) and paragraph (a)(1) of this section apply to the expenses associated with the refreshments that are not excepted under section 274(e)(7) and this paragraph (c)(2)(iv). ( 2 ) Example 2. Employer Q is an automobile service center and provides refreshments in its waiting area.",
      "The refreshments are consumed by Q's employees and customers, and Q reasonably estimates that more than 50 percent of the refreshments are consumed by customers. Under section 274(e)(7) and this paragraph (c)(2)(iv), the expenses associated with the refreshments are not subject to the deduction limitations provided for in paragraph (a) of this section because the food and beverages are primarily consumed by customers. Thus, Q may deduct 100 percent of the food and beverage expenses. ( 3 ) Example 3. Employer R operates a summer camp open to the general public for children and provides breakfast and lunch, as part of the fee to attend camp, both to camp counselors, who are employees, and to camp attendees, who are customers. There are 20 camp counselors and 100 camp attendees. The same type of meal is available to each counselor and attendee, and attendees consume more than 50 percent of the food and beverages.",
      "Under section 274(e)(7) and this paragraph (c)(2)(iv), the expenses associated with the food and beverages are not subject to the deduction limitations in paragraph (a) of this section, because over 50 percent of the food and beverages are consumed by camp attendees and the food and beverages are therefore primarily consumed by the general public. Thus, R may deduct 100 percent of the food and beverage expenses. ( 4 ) Example 4. Employer S provides food and beverages to its employees without charge at a company cafeteria on its premises. Occasionally, customers or other visitors also eat without charge in the cafeteria. The occasional consumption of food and beverages at the company cafeteria by customers and visitors is less than 50 percent of the total amount of food and beverages consumed at the cafeteria. Therefore, the food and beverages are not primarily consumed by the general public, and only the costs attributable to the food and beverages provided to the general public are excepted under section 274(e)(7) and this paragraph (c)(2)(iv).",
      "In addition, the limitations in section 274(k)(1) and paragraph (a)(1) of this section apply to the expenses associated with the food and beverages that are not excepted under section 274(e)(7) and this paragraph (c)(2)(iv). (v) Goods or services sold to customers \u2014(A) In general. In accordance with section 274(e)(8), an expense paid or incurred for food or beverages, to the extent the food or beverages are sold to customers in a bona fide transaction for an adequate and full consideration in money or money's worth, is not subject to the deduction limitations in paragraph (a) of this section. However, money or money's worth does not include payment through services provided. Under this paragraph (c)(2)(v), a restaurant or catering business may deduct 100 percent of its costs for food or beverage items, purchased in connection with preparing and providing meals to its paying customers, which are also consumed at the worksite by employees who work in the employer's restaurant or catering business.",
      "In addition, for purposes of this paragraph (c)(2)(v), the term customer includes anyone, including an employee of the taxpayer, who is sold food or beverages in a bona fide transaction for an adequate and full consideration in money or money's worth. (B) Example. The following example illustrates the application of this paragraph (c)(2)(v): Example. Employer T operates a restaurant. T provides food and beverages to its food service employees before, during, and after their shifts for no consideration. Under section 274(e)(8) and this paragraph (c)(2)(v), the expenses associated with the food and beverages provided to the employees are not subject to the 50 percent deduction limitation in paragraph (a) of this section because the restaurant sells food and beverages to customers in a bona fide transaction for an adequate and full consideration in money or money's worth. Thus, T may deduct 100 percent of the food and beverage expenses. (d) Applicability date. This section applies for taxable years that begin on or after October 9, 2020. [T.D. 9925, 85 FR 64035, Oct. 9, 2020]",
    ],
  },
  {
    id: "acct-2-02",
    name: "Accountants' Reports & Audit Opinions",
    citation: "17 CFR 210.2-02",
    topic: "Accounting",
    pages: [
      "\u00a7 210.2-02 Accountants' reports and attestation reports. (a) Technical requirements for accountants' reports. The accountant's report: (1) Shall be dated; (2) Shall be signed manually; (3) Shall indicate the city and State where issued; and (4) Shall identify without detailed enumeration the financial statements covered by the report. (b) Representations as to the audit included in accountants' reports. The accountant's report: (1) Shall state the applicable professional standards under which the audit was conducted; and (2) Shall designate any auditing procedures deemed necessary by the accountant under the circumstances of the particular case, which have been omitted, and the reasons for their omission. Nothing in this rule shall be construed to imply authority for the omission of any procedure which independent accountants would ordinarily employ in the course of an audit made for the purpose of expressing the opinions required by paragraph (c) of this section. (c) Opinions to be expressed in accountants' reports. The accountant's report shall state clearly:",
      "(1) The opinion of the accountant in respect of the financial statements covered by the report and the accounting principles and practices reflected therein; and (2) the opinion of the accountant as to the consistency of the application of the accounting principles, or as to any changes in such principles which have a material effect on the financial statements. (d) Exceptions identified in accountants' reports. Any matters to which the accountant takes exception shall be clearly identified, the exception thereto specifically and clearly stated, and, to the extent practicable, the effect of each such exception on the related financial statements given. (See section 101 of the Codification of Financial Reporting Policies.) (e) Paragraph (e) of this section applies only to registrants that are providing financial statements in a filing for a period with respect to which Arthur Andersen LLP or a foreign affiliate of Arthur Andersen LLP (\u201cAndersen\u201d) issued an accountants' report.",
      "Notwithstanding any other Commission rule or regulation, a registrant that cannot obtain an accountants' report that meets the technical requirements of paragraph (a) of this section after reasonable efforts may include in the document a copy of the latest signed and dated accountants' report issued by Andersen for such period in satisfaction of that requirement, if prominent disclosure that the report is a copy of the previously issued Andersen accountants' report and that the report has not been reissued by Andersen is set forth on such copy. (f) Attestation report on internal control over financial reporting.",
      "(1) Every registered public accounting firm that issues or prepares an accountant's report for a registrant, other than a registrant that is neither an accelerated filer nor a large accelerated filer (as defined in \u00a7 240.12b-2 of this chapter), or is an emerging growth company, as defined in Rule 405 of the Securities Act (\u00a7 230.405 of this chapter) or Rule 12b-2 of the Exchange Act (\u00a7 240.12b-2 of this chapter), or an investment company registered under Section 8 of the Investment Company Act of 1940 (15 U.S.C. 80a-8), that is included in an annual report required by section 13(a) or 15(d) of the Securities Exchange Act of 1934 (15 U.S.C. 78a et seq. ) containing an assessment by management of the effectiveness of the registrant's internal control over financial reporting must include an attestation report on internal control over financial reporting.",
      "(2) If an attestation report on internal control over financial reporting is included in an annual report required by section 13(a) or 15(d) of the Securities Exchange Act of 1934 (15 U.S.C. 78a et seq. ), it shall clearly state the opinion of the accountant, either unqualified or adverse, as to whether the registrant maintained, in all material respects, effective internal control over financial reporting, except in the rare circumstance of a scope limitation that cannot be overcome by the registrant or the registered public accounting firm which would result in the accounting firm disclaiming an opinion. The attestation report on internal control over financial reporting shall be dated, signed manually, identify the period covered by the report and indicate that the accountant has audited the effectiveness of internal control over financial reporting. The attestation report on internal control over financial reporting may be separate from the accountant's report. (g) Attestation report on assessment of compliance with servicing criteria for asset-backed securities.",
      "The attestation report on assessment of compliance with servicing criteria for asset-backed securities, as required by \u00a7 240.13a-18(c) or \u00a7 240.15d-18(c) of this chapter, shall be dated, signed manually, identify the period covered by the report and clearly state the opinion of the registered public accounting firm as to whether the asserting party's assessment of compliance with the servicing criteria is fairly stated in all material respects, or must include an opinion to the effect that an overall opinion cannot be expressed. If an overall opinion cannot be expressed, explain why. [37 FR 14594, July 21, 1972, as amended at 41 FR 35479, Aug. 23, 1976; 45 FR 63668, Sept. 25, 1980; 50 FR 25215, June 18, 1985; 67 FR 13533, Mar. 22, 2002; 68 FR 36660, June 18, 2003; 70 FR 1593, Jan. 7, 2005; 72 FR 35321, June 27, 2007; 75 FR 57387, Sept. 21, 2010; 82 FR 17551, Apr. 12, 2017; 83 FR 50198, Oct. 4, 2018]",
    ],
  },
  {
    id: "inv-15l-1",
    name: "Regulation Best Interest",
    citation: "17 CFR 240.15l-1",
    topic: "Investing",
    pages: [
      "\u00a7 240.15l-1 Regulation best interest. (a) Best interest obligation. (1) A broker, dealer, or a natural person who is an associated person of a broker or dealer, when making a recommendation of any securities transaction or investment strategy involving securities (including account recommendations) to a retail customer, shall act in the best interest of the retail customer at the time the recommendation is made, without placing the financial or other interest of the broker, dealer, or natural person who is an associated person of a broker or dealer making the recommendation ahead of the interest of the retail customer. (2) The best interest obligation in paragraph (a)(1) of this section shall be satisfied if: (i) Disclosure obligation. The broker, dealer, or natural person who is an associated person of a broker or dealer, prior to or at the time of the recommendation, provides the retail customer, in writing, full and fair disclosure of: (A) All material facts relating to the scope and terms of the relationship with the retail customer, including:",
      "( 1 ) That the broker, dealer, or such natural person is acting as a broker, dealer, or an associated person of a broker or dealer with respect to the recommendation; ( 2 ) The material fees and costs that apply to the retail customer's transactions, holdings, and accounts; and ( 3 ) The type and scope of services provided to the retail customer, including any material limitations on the securities or investment strategies involving securities that may be recommended to the retail customer; and (B) All material facts relating to conflicts of interest that are associated with the recommendation. (ii) Care obligation. The broker, dealer, or natural person who is an associated person of a broker or dealer, in making the recommendation, exercises reasonable diligence, care, and skill to: (A) Understand the potential risks, rewards, and costs associated with the recommendation, and have a reasonable basis to believe that the recommendation could be in the best interest of at least some retail customers;",
      "(B) Have a reasonable basis to believe that the recommendation is in the best interest of a particular retail customer based on that retail customer's investment profile and the potential risks, rewards, and costs associated with the recommendation and does not place the financial or other interest of the broker, dealer, or such natural person ahead of the interest of the retail customer; (C) Have a reasonable basis to believe that a series of recommended transactions, even if in the retail customer's best interest when viewed in isolation, is not excessive and is in the retail customer's best interest when taken together in light of the retail customer's investment profile and does not place the financial or other interest of the broker, dealer, or such natural person making the series of recommendations ahead of the interest of the retail customer. (iii) Conflict of interest obligation. The broker or dealer establishes, maintains, and enforces written policies and procedures reasonably designed to:",
      "(A) Identify and at a minimum disclose, in accordance with paragraph (a)(2)(i) of this section, or eliminate, all conflicts of interest associated with such recommendations; (B) Identify and mitigate any conflicts of interest associated with such recommendations that create an incentive for a natural person who is an associated person of a broker or dealer to place the interest of the broker, dealer, or such natural person ahead of the interest of the retail customer; (C)( 1 ) Identify and disclose any material limitations placed on the securities or investment strategies involving securities that may be recommended to a retail customer and any conflicts of interest associated with such limitations, in accordance with subparagraph (a)(2)(i), and ( 2 ) Prevent such limitations and associated conflicts of interest from causing the broker, dealer, or a natural person who is an associated person of the broker or dealer to make recommendations that place the interest of the broker, dealer, or such natural person ahead of the interest of the retail customer;",
      "and (D) Identify and eliminate any sales contests, sales quotas, bonuses, and non-cash compensation that are based on the sales of specific securities or specific types of securities within a limited period of time. (iv) Compliance obligation. In addition to the policies and procedures required by paragraph (a)(2)(iii) of this section, the broker or dealer establishes, maintains, and enforces written policies and procedures reasonably designed to achieve compliance with Regulation Best Interest. (b) Definitions. Unless otherwise provided, all terms used in this rule shall have the same meaning as in the Securities Exchange Act of 1934. In addition, the following definitions shall apply for purposes of this section: (1) Retail customer means a natural person, or the legal representative of such natural person, who: (i) Receives a recommendation of any securities transaction or investment strategy involving securities from a broker, dealer, or a natural person who is an associated person of a broker or dealer;",
      "and (ii) Uses the recommendation primarily for personal, family, or household purposes. (2) Retail customer investment profile includes, but is not limited to, the retail customer's age, other investments, financial situation and needs, tax status, investment objectives, investment experience, investment time horizon, liquidity needs, risk tolerance, and any other information the retail customer may disclose to the broker, dealer, or a natural person who is an associated person of a broker or dealer in connection with a recommendation. (3) Conflict of interest means an interest that might incline a broker, dealer, or a natural person who is an associated person of a broker or dealer \u2014consciously or unconsciously\u2014to make a recommendation that is not disinterested. [84 FR 33491, July 12, 2019]",
    ],
  },
];

export const getDoc = (id: string): DemoDoc | undefined =>
  DEMO_DOCS.find((d) => d.id === id);
